version: '3.1'

services: 
  db: 
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql:/var/lib/mysql 
    restart: always
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=agendaPetshop
      - MYSQL_USER=sabrina
      - MYSQL_PASSWORD=123456